apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-reading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convert-reading
  template:
    metadata:
      labels:
        app: convert-reading
    spec:
      containers:
      - name: convert-reading
        image: gcr.io/your-project-id/convert-reading:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: convert-reading
spec:
  selector:
    app: convert-reading
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer